#!/bin/bash

#    This file is part of the vkdbg distribution (https://github.com/Group-IB/vkdbg).
#    Copyright (C) 2021 Timur Chernykh
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_VKDBG_PREFIX="vkgdb:"

log_continue() {
    local len=${#_VKDBG_PREFIX}
    spacer=$(printf "%*s" $(($len + 4)))
    echo "$spacer $1"
}

log_and_read() {
    local msg=$1
    local out
    read -r -p "[>] $_VKDBG_PREFIX $msg" out
    echo "$out"
}

log_info() {
    echo "[+] $_VKDBG_PREFIX $1"
}

log_warning() {
    echo "[!] $_VKDBG_PREFIX $1"
}

log_error() {
    echo "[-] $_VKDBG_PREFIX $1"
}
