#!/bin/bash

#    This file is part of the vkdbg distribution (https://github.com/Group-IB/vkdbg).
#    Copyright (C) 2021 Timur Chernykh
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

vkdbg_file="${BASH_SOURCE[0]}"
if [[ -L "$vkdbg_file" ]]; then
    vkdbg_file=$(readlink -f "$vkdbg_file")
fi

_VKDBG_ROOT_DIR="$(cd "$(dirname "$vkdbg_file")" &>/dev/null && pwd)"

source "$_VKDBG_ROOT_DIR/scripts/sh/checks"
source "$_VKDBG_ROOT_DIR/scripts/sh/bundle"
source "$_VKDBG_ROOT_DIR/scripts/sh/unpack"
source "$_VKDBG_ROOT_DIR/scripts/sh/env"
source "$_VKDBG_ROOT_DIR/scripts/sh/log"
source "$_VKDBG_ROOT_DIR/scripts/sh/vm"

check_all_vkdbg_deps

while (("$#")); do
    case "$1" in
    vm)
        shift && vkdbg_vm_cmd "$@"
        exit 0
        ;;
    bundle)
        shift && vkdbg_bundle_cmd "$@"
        exit 0
        ;;
    *)
        log_error "Unknown command $1"
        exit 1
        ;;
    esac
    shift
done
